In [4]:
import numpy as np
np.random.seed()
arr=np.random.randint(0,10,size=(3,4))#任务1
reshaped_arr=arr.reshape(4,3).T#任务2
filtered_arr=arr[arr>5]#任务3
print("原数组:\n", arr)
print("变形并转置:\n", reshaped_arr)
print("大于 5 的元素:", filtered_arr)

原数组:
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
变形并转置:
 [[6 4 2 4]
 [3 6 6 3]
 [7 9 7 7]]
大于 5 的元素: [6 7 6 9 6 7 7]


In [5]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # 把 Python 列表转换为 NumPy 数组

row_slice = arr[1,0:3]      #任务1
third_column =arr[:,2]    # 任务2
odd_rows =arr[::2,:]        # 任务3

print(row_slice)
print(third_column)
print(odd_rows)

[5 6 7]
[ 3  7 11]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [6]:
np.random.seed() 
A = np.random.randint(1, 10, size=(2, 3)) 
B = np.random.randint(1, 10, size=(2, 3)) 

multiply_elementwise = A*B  # 任务1
matrix_product =  A @ B.T   

small = np.array([[1, 2], [3, 4]])  # 任务2
col_sum =  np.sum(small,axis=0)             
row_sum =  np.sum(small,axis=1)             

x = np.array([1.2, 3.5, 2.8])  # 任务3
mean_x =  np.mean(x)              
std_x =   np.std(x)              
round_x = np.round(x)             

print("A:\n", A)
print("B:\n", B)
print("A * B:\n", multiply_elementwise)
print("A @ B.T:\n", matrix_product) 
print("列求和 axis=0:", col_sum)
print("行求和 axis=1:", row_sum)
print("均值:", mean_x)
print("标准差:", std_x)
print("四舍五入:", round_x)

A:
 [[7 4 8]
 [5 7 3]]
B:
 [[7 8 5]
 [4 8 8]]
A * B:
 [[49 32 40]
 [20 56 24]]
A @ B.T:
 [[121 124]
 [106 100]]
列求和 axis=0: [4 6]
行求和 axis=1: [3 7]
均值: 2.5
标准差: 0.9626352718795768
四舍五入: [1. 4. 3.]


In [47]:
np.random.seed() 
arr = np.random.rand(10)  #任务1

normalized = (arr - arr.min())/(arr.max()-arr.min())*100  #任务2
cum_sum = np.cumsum(normalized)     # 任务3
cum_max = np.maximum.accumulate(normalized)     

print("原数组:", np.round(arr, 3)) 
print("归一化:", np.round(normalized, 2)) 
print("累计和:", np.round(cum_sum, 2))
print("累计最大值:", np.round(cum_max, 2))

原数组: [0.39  0.738 0.842 0.251 0.881 0.289 0.223 0.139 0.71  0.87 ]
归一化: [ 33.77  80.81  94.76  15.1  100.    20.23  11.27   0.    77.    98.61]
累计和: [ 33.77 114.58 209.34 224.44 324.44 344.67 355.94 355.94 432.95 531.55]
累计最大值: [ 33.77  80.81  94.76  94.76 100.   100.   100.   100.   100.   100.  ]
